#!/bin/bash
cmake -DPLUGIN_IMAGE=ON  -DPLUGIN_CGALPLUGIN=ON -DPLUGIN_MANUALMAPPING=ON \
	-DPLUGIN_SOFAALLCOMMONCOMPONENTS=ON -DPLUGIN_SOFADISTANCEGRID=ON \
	-DPLUGIN_SOFAEULERIANFLUID=ON -DPLUGIN_SOFAPYTHON=ON -DPLUGIN_VOLUMETRICRENDERING=ON \
	-DSOFA_BUILD_METIS=ON -DSOFA_BUILD_MINIFLOWVR=ON -DPLUGIN_MULTITHREADINBG=ON \
	../src #-DPLUGIN_PSL=ON -DPLUGIN_VolumetricRendering=ON -DPLUGIN_SOFACUDA=ON

echo -e "\nNow making\n\n"

make -j8

echo -e "\n\nNow installing in build folder\n\ns"

make install
